# Generated by Django 6.0.5 on 2026-05-22 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Ex: 📚 ou classe CSS', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Capa')),
                ('file', models.FileField(upload_to='protected/ebooks/', verbose_name='Arquivo PDF')),
                ('preview', models.FileField(blank=True, null=True, upload_to='previews/', verbose_name='Preview gratuito')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço promocional')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Aguardando Aprovação'), ('published', 'Publicado'), ('rejected', 'Rejeitado')], default='draft', max_length=20, verbose_name='Status')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Páginas')),
                ('language', models.CharField(default='Português', max_length=50, verbose_name='Idioma')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'eBook',
                'verbose_name_plural': 'eBooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
