# Generated by Django 6.0.5 on 2026-05-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file_epub',
            field=models.FileField(blank=True, null=True, upload_to='protected/ebooks/epub/', verbose_name='Arquivo EPUB'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, upload_to='protected/ebooks/mobi/', verbose_name='Arquivo MOBI (Kindle)'),
        ),
        migrations.CreateModel(
            name='EbookBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do bônus')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/bonus/', verbose_name='Capa do bônus')),
                ('file', models.FileField(blank=True, null=True, upload_to='protected/bonus/', verbose_name='Arquivo PDF')),
                ('file_epub', models.FileField(blank=True, null=True, upload_to='protected/bonus/epub/', verbose_name='Arquivo EPUB')),
                ('file_mobi', models.FileField(blank=True, null=True, upload_to='protected/bonus/mobi/', verbose_name='Arquivo MOBI (Kindle)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='products.ebook', verbose_name='eBook principal')),
            ],
            options={
                'verbose_name': 'eBook Bônus',
                'verbose_name_plural': 'eBooks Bônus',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
