# Generated by Django 6.0.5 on 2026-08-03 16:18

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ebook_file_epub_ebook_file_mobi_ebookbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_epub',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/epub/', verbose_name='Arquivo EPUB'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/mobi/', verbose_name='Arquivo MOBI (Kindle)'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='bonus/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='file_epub',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='bonus/epub/', verbose_name='Arquivo EPUB'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='bonus/mobi/', verbose_name='Arquivo MOBI (Kindle)'),
        ),
    ]
