# Generated by Django 6.0.5 on 2026-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ajustar_nomes_arquivos_protegidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço físico + digital (combo)'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='physical_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço do livro físico'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='physical_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque físico'),
        ),
    ]
