# Generated by Django 6.0.5 on 2026-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ebook_combo_price_ebook_physical_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='physical_height_cm',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='physical_length_cm',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='physical_weight_g',
            field=models.PositiveIntegerField(default=300, help_text='Peso do livro físico embalado, em gramas.', verbose_name='Peso físico (gramas)'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='physical_width_cm',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='Largura (cm)'),
        ),
    ]
