# Generated by Django 6.0.5 on 2026-08-20 02:06

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_ebook_physical_height_cm_ebook_physical_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='isbn_epub',
            field=models.CharField(blank=True, help_text='ISBN da versão EPUB. Obrigatório se o arquivo EPUB for enviado.', max_length=13, verbose_name='ISBN EPUB'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='isbn_mobi',
            field=models.CharField(blank=True, help_text='ISBN da versão MOBI. Obrigatório se o arquivo MOBI for enviado.', max_length=13, verbose_name='ISBN MOBI (Kindle)'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='isbn_pdf',
            field=models.CharField(blank=True, help_text='ISBN da versão PDF. Obrigatório se o arquivo PDF for enviado.', max_length=13, verbose_name='ISBN PDF'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='isbn_physical',
            field=models.CharField(blank=True, help_text='ISBN da versão física. Obrigatório se o arquivo físico for enviado.', max_length=13, verbose_name='ISBN Físico'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço digital'),
        ),
    ]
