# Generated by Django 6.0.5 on 2026-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_ebook_isbn_epub_ebook_isbn_mobi_ebook_isbn_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='isbn_epub',
            field=models.CharField(blank=True, help_text='ISBN da versão EPUB. Obrigatório se o arquivo EPUB for enviado.', max_length=13, null=True, verbose_name='ISBN EPUB'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='isbn_mobi',
            field=models.CharField(blank=True, help_text='ISBN da versão MOBI. Obrigatório se o arquivo MOBI for enviado.', max_length=13, null=True, verbose_name='ISBN MOBI (Kindle)'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='isbn_pdf',
            field=models.CharField(blank=True, help_text='ISBN da versão PDF. Obrigatório se o arquivo PDF for enviado.', max_length=13, null=True, verbose_name='ISBN PDF'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='isbn_physical',
            field=models.CharField(blank=True, help_text='ISBN da versão física. Obrigatório se o arquivo físico for enviado.', max_length=13, null=True, verbose_name='ISBN Físico'),
        ),
    ]
