# Generated by Django 6.0.5 on 2026-08-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_ebook_isbn_epub_alter_ebook_isbn_mobi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo enviado ao escritor quando o eBook é rejeitado.', verbose_name='Justificativa da rejeição'),
        ),
    ]
