# Generated by Django 6.0.5 on 2026-08-21 04:42

import core.storages
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_ebook_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(upload_to='covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'], 'Formato não permitido. Use JPG, PNG, WEBP ou GIF.')], verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi'], 'Formato não permitido. Use PDF, EPUB ou MOBI.')], verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_epub',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/epub/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi'], 'Formato não permitido. Use PDF, EPUB ou MOBI.')], verbose_name='Arquivo EPUB'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='ebooks/mobi/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi'], 'Formato não permitido. Use PDF, EPUB ou MOBI.')], verbose_name='Arquivo MOBI (Kindle)'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='previews/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], 'Formato não permitido. Use PDF, JPG, PNG, WEBP ou GIF.')], verbose_name='Preview gratuito'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/bonus/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'], 'Formato não permitido. Use JPG, PNG, WEBP ou GIF.')], verbose_name='Capa do bônus'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='bonus/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi'], 'Formato não permitido. Use PDF, EPUB ou MOBI.')], verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='file_epub',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='bonus/epub/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi'], 'Formato não permitido. Use PDF, EPUB ou MOBI.')], verbose_name='Arquivo EPUB'),
        ),
        migrations.AlterField(
            model_name='ebookbonus',
            name='file_mobi',
            field=models.FileField(blank=True, null=True, storage=core.storages.ProtectedFileSystemStorage(), upload_to='bonus/mobi/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi'], 'Formato não permitido. Use PDF, EPUB ou MOBI.')], verbose_name='Arquivo MOBI (Kindle)'),
        ),
    ]
