# Generated by Django 6.0.5 on 2026-08-25 00:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_ebook_cover_alter_ebook_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('5.90'))], verbose_name='Preço físico + digital (combo)'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('5.90'))], verbose_name='Preço promocional'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='physical_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('5.90'))], verbose_name='Preço do livro físico'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('5.90'))], verbose_name='Preço digital'),
        ),
    ]
