# Generated by Django 6.0.5 on 2026-05-22 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Downloads realizados')),
                ('max_downloads', models.PositiveIntegerField(default=5, verbose_name='Máximo de downloads')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_download_at', models.DateTimeField(blank=True, null=True, verbose_name='Último download')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='payments.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Token de Download',
                'verbose_name_plural': 'Tokens de Download',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do download')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='delivery.downloadtoken', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Log de Download',
                'verbose_name_plural': 'Logs de Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
