# Generated by Django 6.0.5 on 2026-08-04 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting', 'Aguardando envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='awaiting', max_length=20, verbose_name='Status')),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frete (R$)')),
                ('offer_id', models.CharField(blank=True, max_length=200, verbose_name='ID da oferta no ME')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Transportadora')),
                ('delivery_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo (dias úteis)')),
                ('quote_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload da cotação')),
                ('melhor_envios_id', models.CharField(blank=True, max_length=200, verbose_name='ID do envio no ME')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='Código de rastreio')),
                ('tracking_url', models.URLField(blank=True, verbose_name='URL de rastreio')),
                ('label_pdf', models.FileField(blank=True, null=True, upload_to='labels/', verbose_name='Etiqueta (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Postado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Escritor')),
            ],
            options={
                'verbose_name': 'Pacote de Envio',
                'verbose_name_plural': 'Pacotes de Envio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Nome remetente')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('me_access_token', models.TextField(blank=True, verbose_name='Access token ME')),
                ('me_refresh_token', models.TextField(blank=True, verbose_name='Refresh token ME')),
                ('me_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expira em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profile', to=settings.AUTH_USER_MODEL, verbose_name='Escritor')),
            ],
            options={
                'verbose_name': 'Perfil de Envio',
                'verbose_name_plural': 'Perfis de Envio',
            },
        ),
    ]
