# Generated by Django 6.0.5 on 2026-08-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_shipment_shippingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='print_url',
            field=models.URLField(blank=True, verbose_name='URL de impressão da etiqueta'),
        ),
        migrations.AddField(
            model_name='shippingprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
    ]
