# Generated by Django 6.0.5 on 2026-08-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_shipment_print_url_shippingprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Aguardando envio'), ('ready', 'Aguardando postagem'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='awaiting', max_length=20, verbose_name='Status'),
        ),
    ]
