# Generated by Django 6.0.5 on 2026-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_shipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditoraShippingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, max_length=200, verbose_name='Titular da conta')),
                ('me_access_token', models.TextField(blank=True, verbose_name='Access token ME')),
                ('me_refresh_token', models.TextField(blank=True, verbose_name='Refresh token ME')),
                ('me_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expira em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta Melhor Envios da Editora',
                'verbose_name_plural': 'Contas Melhor Envios da Editora',
            },
        ),
        migrations.AddField(
            model_name='shippingprofile',
            name='uses_editora_account',
            field=models.BooleanField(default=True, verbose_name='Usar conta da Editora no Melhor Envios'),
        ),
    ]
