# Generated by Django 6.0.5 on 2026-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cpf_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='É escritor'),
        ),
    ]
