# Generated by Django 6.0.5 on 2026-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Aceitou os termos da loja'),
        ),
    ]
