# Generated by Django 6.0.5 on 2026-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0005_ebook_combo_price_ebook_physical_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Físico'), ('combo', 'Físico + Digital')], default='digital', max_length=20, verbose_name='Formato'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'ebook', 'variant')},
        ),
    ]
