# Generated by Django 6.0.5 on 2026-05-22 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor pago')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Taxa da plataforma')),
                ('producer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor para o produtor')),
                ('gateway', models.CharField(blank=True, max_length=50, verbose_name='Gateway')),
                ('gateway_order_id', models.CharField(blank=True, max_length=200, verbose_name='ID no gateway')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID do pagamento')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Pagamento'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Email do comprador')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nome do comprador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.ebook', verbose_name='eBook')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, verbose_name='Método')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta bruta do gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
