# Generated by Django 6.0.5 on 2026-06-02 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Comissão da plataforma (%)')),
                ('min_withdraw', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Valor mínimo para saque (R$)')),
                ('withdraw_info', models.TextField(blank=True, default='Os saques são processados em até 5 dias úteis via PIX.', verbose_name='Instruções de saque')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Plataforma',
                'verbose_name_plural': 'Configuração da Plataforma',
            },
        ),
        migrations.CreateModel(
            name='ProducerBankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_type', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'Email'), ('phone', 'Telefone'), ('random', 'Chave aleatória')], max_length=20, verbose_name='Tipo de chave PIX')),
                ('pix_key', models.CharField(max_length=200, verbose_name='Chave PIX')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo do titular')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_data', to=settings.AUTH_USER_MODEL, verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Dados Bancários',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor solicitado')),
                ('pix_key', models.CharField(max_length=200, verbose_name='Chave PIX usada')),
                ('pix_type', models.CharField(max_length=20, verbose_name='Tipo de chave PIX')),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovação'), ('approved', 'Aprovado'), ('paid', 'Pago'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Observação do admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL, verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Solicitação de Saque',
                'verbose_name_plural': 'Solicitações de Saque',
                'ordering': ['-created_at'],
            },
        ),
    ]
