# Generated by Django 6.0.5 on 2026-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_platformconfig_producerbankdata_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/withdraws/', verbose_name='Comprovante de pagamento'),
        ),
    ]
