# Generated by Django 6.0.5 on 2026-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_withdrawrequest_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='pix_holder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do titular'),
        ),
    ]
