# Generated by Django 6.0.5 on 2026-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_withdrawrequest_pix_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_complement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Físico'), ('combo', 'Físico + Digital')], default='digital', max_length=20, verbose_name='Formato'),
        ),
    ]
