# Generated by Django 6.0.5 on 2026-08-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_cancel_requested_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
    ]
