# Generated by Django 6.0.5 on 2026-08-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_order_shipping_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('awaiting', 'Aguardando envio'), ('ready', 'Aguardando postagem'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='', max_length=20, verbose_name='Status do envio'),
        ),
    ]
