# Generated by Django 6.0.5 on 2026-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='max_cover_size_mb',
            field=models.PositiveIntegerField(default=2, verbose_name='Tamanho máximo de upload — Capas (MB)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='max_preview_size_mb',
            field=models.PositiveIntegerField(default=3, verbose_name='Tamanho máximo de upload — Preview (MB)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='max_upload_size_mb',
            field=models.PositiveIntegerField(default=5, verbose_name='Tamanho máximo de upload — eBooks (MB)'),
        ),
    ]
