# Generated by Django 6.0.5 on 2026-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_platformconfig_max_cover_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado por cada ebook vendido, além da comissão percentual.', max_digits=8, verbose_name='Taxa fixa por venda (R$)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='store_terms',
            field=models.TextField(blank=True, help_text='Texto dos termos que o escritor deve aceitar.', verbose_name='Termos da Loja'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='terms_enabled',
            field=models.BooleanField(default=False, help_text='Se ativo, escritores devem aceitar os termos antes de publicar.', verbose_name='Termos ativados'),
        ),
    ]
