# Generated by Django 6.0.5 on 2026-08-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_platformconfig_fixed_fee_platformconfig_store_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='isbn_required',
            field=models.BooleanField(default=False, help_text='Se ativo, é obrigatório informar o ISBN correspondente ao enviar PDF/EPUB/MOBI ou ao oferecer a versão física. Formato e duplicidade continuam validados mesmo desativado.', verbose_name='Exigir ISBN por formato'),
        ),
    ]
