# Generated by Django 6.0.5 on 2026-09-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_platformconfig_isbn_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do destinatário'),
        ),
    ]
